# Example GitLab CI configuration

stages:
  - test
  - coverage

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - cov_env/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv cov_env
  - source cov_env/bin/activate
  - pip install -r requirements.txt

test:pytest:
  stage: test
  script:
    - pytest -v --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

coverage:
  stage: coverage
  script:
    - pytest --cov=src --cov-report=html --cov-report=xml --cov-report=term
    - coverage report
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage_html/
    expire_in: 30 days

test:bazel:
  stage: test
  image: gcr.io/bazel-public/bazel:latest
  script:
    - bazel test //...
  allow_failure: true
